---
apiVersion: v2
name: hbase-operator
version: "25.11.0-rc1"
appVersion: "25.11.0-rc1"
description: The Stackable Operator for Apache HBase
home: https://github.com/stackabletech/hbase-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
